services:
  db:
    image: docker.io/postgres:alpine3.23
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-uni_track_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./container:/var/lib/postgresql/data:z

networks:
  default:
    name: uni_track_network
