services:
  db:
    image: docker.io/postgres:alpine3.23
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-uni_track_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./container/pg:/var/lib/postgresql:z

  redis:
    image: docker.io/redis:7.4-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./container/redis:/data:z

networks:
  default:
    name: uni_track_network