 export enum Permission {
    ELDENLORD = 999,
    
    // FOR USERS
    USERS_VIEW = 100,
    USERS_CREATE = 101,
    USERS_EDIT = 102,
    USERS_DELETE = 103,
    
    // FOR AUTHORIZATION
    AUTHORIZATION_VIEW = 200,
    AUTHORIZATION_CREATE = 201,
    AUTHORIZATION_EDIT = 202,
    AUTHORIZATION_DELETE = 203,
 }